version: '3'

services:
  app:
    build:
      dockerfile: docker/Dockerfile
    command: ./wait-for-postgres.sh db ./DemonstrationServiceL0
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: demo_service_database
      POSTGRES_USER: Pavel
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "demo_service_database", "-U", "Pavel" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql

#  docker exec -it demonstrationservicel0-db-1 psql -U Pavel -d demo_service_database
