version: '4'

services:
  handler:
    build:
      dockerfile: docker/DockerfileHandler
    command: ./wait-for-postgres.sh db ./DemonstrationServiceL0
    ports:
      - "8080:8080"
    depends_on:
      - db
      - nats-streaming
    environment:
      - POSTGRES_DB=demo_service_database
      - POSTGRES_USER=Pavel
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_HOST=db
      - NATS_CLUSTER_ID=nats-cluster

  sender:
    build:
      dockerfile: docker/DockerfileSender
    depends_on:
      - db
      - nats-streaming
    environment:
      - NATS_CLUSTER_ID=nats-cluster

  db:
    restart: always
    build:
      dockerfile: docker/DockerfileDB
    environment:
      POSTGRES_DB: demo_service_database
      POSTGRES_USER: Pavel
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"

  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [ "-cid", "nats-cluster"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

#  docker exec -it demonstrationservicel0-db-1 psql -U Pavel -d demo_service_database
