version: '3.8'

services:
  handler:
    build:
      dockerfile: docker/DockerfileHandler
    command: ./DemonstrationServiceL0
    ports:
      - "8081:8080"
    depends_on:
      - db
      - nats-streaming
    environment:
      - POSTGRES_DB=demo_service_database
      - POSTGRES_USER=Pavel
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_HOST=db
      - NATS_CLUSTER_ID=nats-cluster

  sender:
    build:
      dockerfile: docker/DockerfileSender
    depends_on:
      - nats-streaming
    environment:
      - NATS_CLUSTER_ID=nats-cluster

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: demo_service_database
      POSTGRES_USER: Pavel
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql

  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [ "-cid", "nats-cluster"]

#  docker exec -it demonstrationservicel0-db-1 psql -U Pavel -d demo_service_database
